# This works but adjusting it could lead to crashing.

---

engine:
  # 0 to auto-detect number of threads if possible; this is the default
  #  threads: 4
  logs:
    console_level: info
    console_sources:
      - pulsar
      # - pulsar.locking
      - jackaudio
    memory_level: debug
    # this will use a lot of CPU
    # memory_level: trace

templates:
  gain:
    class: pulsar::ladspa::node
    plugin:
      filename: /usr/lib/ladspa/amp.so
      id: 1048
  compressor:
    class: pulsar::ladspa::node
    plugin:
      filename: /usr/local/lib/ladspa/ZamComp-ladspa.so
    config:
      Knee: 0
      Threshold: 0
      Makeup: 0
      Sidechain: 1
  gate:
    class: pulsar::ladspa::node
    plugin:
      filename: /usr/local/lib/ladspa/ZamGate-ladspa.so
  delay:
    class: pulsar::ladspa::node
    plugin:
      filename: /usr/lib/ladspa/delay_1898.so
      id: 1899
  tube:
    class: pulsar::ladspa::node
    plugin:
      filename: /usr/local/lib/ladspa/ZamTube-ladspa.so

chains:
  remove_squelch_tail:
    channels: 1
    state:
      - gate:*
    forward:
      in_1:
        - delay:Input
        - gate:Sidechain Input
    nodes:
      - name: delay
        template: delay
        config:
          Delay Time (s): .1
          Max Delay (s): .2
        link:
          Output: gate:Audio Input 1

      - name: gate
        template: gate
        config:
          Sidechain: 1
          Threshold: -65
          Attack: 25
          Release: 25
          Max gate close: -.inf
        forward:
          Audio Output 1: remove_squelch_tail:out_1

daemons:
  watch_jack_connections:
    class: pulsar::jackaudio::connections
    config:
      connect:
        # - [ system:capture_1, pulsar:left_in ]
        # - [ system:capture_2, pulsar:right_in ]
        # - [ pulsar:left_out, system:playback_1 ]
        # - [ pulsar:right_out, system:playback_2 ]

domain:
  config:
    sample_rate: 48000
    buffer_size: 256
  nodes:
    - name: jack
      class: pulsar::jackaudio::node
      config:
        client_name: pulsar
        # reduce sensitivity because of interrupt isues on test
        # hardware
        watchdog_timeout_ms: 100
      sends:
        - left_out
        - right_out
        - demod_out
        - mono_out
        - left_loop_out
        - right_loop_out
        - left_tube_out
        - right_tube_out
      receives: [ left_in, right_in, demod_in ]
      link:
        left_in:
          - comp_left:*
          - jack:left_loop_out
          - tube_left:*
        right_in:
          - comp_right:*
          - jack:right_loop_out
          - tube_right:*
        demod_in: tail_eater:in_1

    - name: tail_eater
      chain: remove_squelch_tail
      link: tail_tube

    - name: tail_tube
      template: tube
      link:
        Audio Output 1: tail_enable_gate:Audio Input 1

    - name: tail_enable_gate
      template: gate
      config:
        Threshold: +.inf
      link:
        Audio Output 1: jack:demod_out

    - name: comp_left
      template: compressor
      link: gain_left1

    - name: comp_right
      template: compressor
      link: gain_right1

    - name: gain_left1
      template: gain
      config:
        Gain: .5
      link:
        Output:
          - gain_left2
          - jack:mono_out

    - name: gain_right1
      template: gain
      config:
        Gain: .5
      link:
        Output:
          - gain_right2
          - jack:mono_out

    - name: gain_left2
      template: gain
      config:
        Gain: 2
      link:
        Output: jack:left_out

    - name: gain_right2
      template: gain
      config:
        Gain: 2
      link:
        Output: jack:right_out

    - name: tube_left
      template: tube
      link:
        Audio Output 1: jack:left_tube_out

    - name: tube_right
      template: tube
      link:
        Audio Output 1: jack:right_tube_out
